/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-13 08:04:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class explore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>explore</title>\n");
      out.write("<script src='https://code.jquery.com/jquery-3.4.0.js'></script>\n");
      out.write("<!-- RESET -->\n");
      out.write("<link href=\"./css/html5_reset.css\" rel=\"stylesheet\">\n");
      out.write("<!-- HEADER CSS -->\n");
      out.write("<link href=\"./css/header.css\" rel=\"stylesheet\">\n");
      out.write("<!-- SECTION CSS -->\n");
      out.write("<link href=\"./css/section.css\" rel=\"stylesheet\">\n");
      out.write("<!-- FOOTER CSS -->\n");
      out.write("<link href=\"./css/footer.css\" rel=\"stylesheet\">\n");
      out.write("<script>\n");
      out.write("$(function(){\n");
      out.write("   $(window).scroll(function(){\n");
      out.write("   var navbar = $(this).scrollTop();\n");
      out.write("   console.log(navbar);\n");
      out.write("   var $header = $('header');\n");
      out.write("   if(navbar > 0){\n");
      out.write("       $header.addClass('activated');\n");
      out.write("   }else{\n");
      out.write("       $header.removeClass('activated');\n");
      out.write("   }\n");
      out.write("   $(\".search-term\").click(function(){\n");
      out.write("\t   $(\"#hidden_term\").attr(\"style\", \"visibility:visible\")\n");
      out.write("   })\n");
      out.write("   $(\".hidden_term_close\").click(function(){\n");
      out.write("\t   $(\"#hidden_term\").attr(\"style\", \"visibility:hidden\")\n");
      out.write("   })\n");
      out.write("   \n");
      out.write(" })\n");
      out.write("})\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("\tmargin: 0;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 100%;\n");
      out.write("\tline-height: 1.43;\n");
      out.write("\t    color: rgba(0, 0, 0, 0.87);\n");
      out.write("    margin: 0;\n");
      out.write("    font-size: 0.875rem;\n");
      out.write("    font-family: Inter,sans-serif;\n");
      out.write("    font-weight: 400;\n");
      out.write("    line-height: 1.43;\n");
      out.write("}\n");
      out.write("div {\n");
      out.write("\tdisplay: block;\n");
      out.write("}\n");
      out.write("input {\n");
      out.write("\tborder: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<!-- MAIN -->\n");
      out.write("<style>\n");
      out.write("main {\n");
      out.write("\twidth: 100%;\n");
      out.write("\tmax-width: 100vw;\n");
      out.write("}\n");
      out.write("section {\n");
      out.write("    padding: 45px 0;\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    align-items: center;\n");
      out.write("    position: relative;\n");
      out.write("    background: #f9fafc;\n");
      out.write("    z-index: 0;\n");
      out.write("}\n");
      out.write("#home {\n");
      out.write("\theight: 350px;\n");
      out.write("}\n");
      out.write("a {\n");
      out.write("\ttext-decoration:none;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<!-- SECTION 2 -->\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".mini{\n");
      out.write("\tpadding: 3px 0;\n");
      out.write("\tbackground-color: white;\n");
      out.write("\tposition: -webkit-sticky;\n");
      out.write("\tposition: sticky;\n");
      out.write("\ttop: 55px;\n");
      out.write("\tz-index: 999;\n");
      out.write("}\n");
      out.write(".mini .container{\n");
      out.write("\twidth:80%;\n");
      out.write("}\n");
      out.write(".mini_row{\n");
      out.write("\tdisplay: flex;\n");
      out.write("\tflex-direction: row;\n");
      out.write("\tpadding: 3px 0;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mini_row button{\n");
      out.write("\tborder: 1px solid rgba(132,146,166,.2)!important;\n");
      out.write("\tcolor: black;\n");
      out.write("\tmargin: 0 8px 0 0;\n");
      out.write("\tfont-weight: normal;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write(".search-term {\n");
      out.write("  display: inline-flex;\n");
      out.write("  align-items: center;\n");
      out.write("  text-align: center;\n");
      out.write("  flex-direction: row;\n");
      out.write("  position: relative\n");
      out.write("}\n");
      out.write(".search-term button{\n");
      out.write("\twidth: 34px;\n");
      out.write("\t--verticalPadding: 0;\n");
      out.write("\t--horizontalPadding: 0;\n");
      out.write("\theight: 34px;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write(".search-term svg{\n");
      out.write("\twidth: 20px;\n");
      out.write("\theight: 20px;\n");
      out.write("\tpadding: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-term {\n");
      out.write("\tborder-radius: 50px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#hidden_term{\n");
      out.write("\tvisibility : hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<!-- SECTION 3 -->\n");
      out.write("<style>\n");
      out.write("#sth{\n");
      out.write("\twidth: 100%;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("#sth .container{\n");
      out.write("\twidth: 80%;\n");
      out.write("\tmargin: 0 auto;\n");
      out.write("\tpadding-top: 15px;\n");
      out.write("\n");
      out.write("}\n");
      out.write("section#store-list {\n");
      out.write("    padding-top: 65px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("section .container .store_list_grid {\n");
      out.write("    display: grid;\n");
      out.write("    grid-column-gap: 30px;\n");
      out.write("    grid-row-gap: 30px;\n");
      out.write("    grid-template-rows: auto;\n");
      out.write("    min-height: 0;\n");
      out.write("    min-width: 0;\n");
      out.write("    grid-template-columns: repeat(3,1fr);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".store_card_image img{\n");
      out.write("    height: 210px;\n");
      out.write("    border-radius: 6px;\n");
      out.write("    width: 100%;\n");
      out.write("    background: #ebf3fe;\n");
      out.write("    border: 0;\n");
      out.write("    position: relative;\n");
      out.write("    transition: .2s ease-in-out;\n");
      out.write("    height: 160px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- HEADER -->\n");
      out.write("\t<header>\n");
      out.write("\t\t<div class=\"header_container\">\n");
      out.write("\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t<img src=\"./images/jaba_english_white.png\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"menu\">\n");
      out.write("\t\t\t\t<button class=\"menu_btn\" value=\"LOG IN\">\n");
      out.write("\t\t\t\t<span>LOG IN</span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t<button class=\"menu_btn\" value=\"SIGN UP\">\n");
      out.write("\t\t\t\t<span>SIGN UP</span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</header>\n");
      out.write("<!-- SECTION -->\n");
      out.write("\t<section id=\"home\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<h1>\n");
      out.write("\t\t\t\tNo PickUp Line<br> <br>\n");
      out.write("\t\t\t</h1>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</section>\n");
      out.write("<!-- SECTION 2 -->\n");
      out.write("\t<section id=\"search\" class=\"mini\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"mini_row\">\n");
      out.write("\t\t\t\t<div class=\"time\">\n");
      out.write("\t\t\t\t\t<button>Pick up, ASAP</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"search_loc\">\n");
      out.write("\t\t\t\t\t<button>AVENUE</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"search-term\">\n");
      out.write("\t\t\t\t<button class=\"MuiButtonBase-root MuiIconButton-root search-term__icon  MuiIconButton-sizeSmall jss263\" tabindex=\"0\" type=\"button\">\n");
      out.write("\t\t\t\t<span class=\"MuiIconButton-label\">\n");
      out.write("\t\t\t\t<svg class=\"MuiSvgIcon-root\" focusable=\"false\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" role=\"presentation\">\n");
      out.write("\t\t\t\t<path d=\"M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z\">\n");
      out.write("\t\t\t\t</path>\n");
      out.write("\t\t\t\t</svg>\n");
      out.write("\t\t\t\t</span>\n");
      out.write("\t\t\t\t<div class=\"MuiTouchRipple-root\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"hidden_term\">\n");
      out.write("\t\t\t\t<button class=\"hidden_term_all\">\n");
      out.write("\t\t\t\t\t<div id=\"hidden_input\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"Acai or Latte\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<button class=\"hidden_term_close\">\n");
      out.write("\t\t\t\t\tX\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("<!-- SECTION 3 -->\n");
      out.write("\t<section id=\"sth\">\n");
      out.write("\t\t<div id=\"store_list\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row-head\">\n");
      out.write("\t\t\t\t\t<h2>PICK UP near _________________</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"container\">\t\n");
      out.write("            <div class=\"store_list_grid\" id=\"store_grid\">\n");
      out.write("\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t<div class=\"store_card\">\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_image\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"https://cdn.boppl.me/venues/banner/4652_doughnut_time_degraves_street_banner_1.jpg\" >\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_info\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_name\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>STORE NAME</h3>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_addr\">\n");
      out.write("\t\t\t\t\t\t\t\t<span>distance from here</span>\n");
      out.write("\t\t\t\t\t\t\t\t<span>OPEN TIME</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t<div class=\"store_card\">\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_image\">\n");
      out.write("\t\t\t\t\t\t\t<img >\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_info\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_name\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>STORE NAME</h3>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_addr\">\n");
      out.write("\t\t\t\t\t\t\t\t<span>distance from here</span>\n");
      out.write("\t\t\t\t\t\t\t\t<span>OPEN TIME</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t<div class=\"store_card\">\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_image\">\n");
      out.write("\t\t\t\t\t\t\t<img >\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_info\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_name\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>STORE NAME</h3>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_addr\">\n");
      out.write("\t\t\t\t\t\t\t\t<span>distance from here</span>\n");
      out.write("\t\t\t\t\t\t\t\t<span>OPEN TIME</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t<div class=\"store_card\">\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_image\">\n");
      out.write("\t\t\t\t\t\t\t<img >\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_info\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_name\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>STORE NAME</h3>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_addr\">\n");
      out.write("\t\t\t\t\t\t\t\t<span>distance from here</span>\n");
      out.write("\t\t\t\t\t\t\t\t<span>OPEN TIME</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t<div class=\"store_card\">\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_image\">\n");
      out.write("\t\t\t\t\t\t\t<img >\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_info\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_name\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>STORE NAME</h3>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_addr\">\n");
      out.write("\t\t\t\t\t\t\t\t<span>distance from here</span>\n");
      out.write("\t\t\t\t\t\t\t\t<span>OPEN TIME</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t<div class=\"store_card\">\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_image\">\n");
      out.write("\t\t\t\t\t\t\t<img >\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"store_card_info\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_name\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>STORE NAME</h3>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"store_card_info_addr\">\n");
      out.write("\t\t\t\t\t\t\t\t<span>distance from here</span>\n");
      out.write("\t\t\t\t\t\t\t\t<span>OPEN TIME</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("                \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("        </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\t<!-- FOOTER -->\n");
      out.write("\t<footer> \n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t        <div class=\"footer_logo\">\n");
      out.write("\t            <img src=\"images/jaba_english_white.png\">\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"footer_links\">\n");
      out.write("\t\t        <ul>\n");
      out.write("\t\t            <li class=\"links_head\">JABA for YOUNG&RICH</li>\n");
      out.write("\t\t            <li>WHY JABA?</li>\n");
      out.write("\t\t            <li>PRICING</li>\n");
      out.write("\t\t            <li><a href='#'>PARTNER LOGIN</a></li>\n");
      out.write("\t\t        </ul>\n");
      out.write("\t\t        <ul>\n");
      out.write("\t\t            <li class=\"links_head\">TOP CITIES</li>\n");
      out.write("\t\t            <li>JONGRO</li>\n");
      out.write("\t\t            <li>SEOCHON</li>\n");
      out.write("\t\t            <li>PARIS</li>\n");
      out.write("\t\t        </ul>\n");
      out.write("\t\t        <ul>\n");
      out.write("\t\t            <li class=\"links_head\">SUPPORT</li>\n");
      out.write("\t\t            <li>CUSTOMER HELP</li>\n");
      out.write("\t\t            <li>PARTNER HELP</li>\n");
      out.write("\t\t            <li>SUGGEST STH</li>\n");
      out.write("\t\t        </ul>\n");
      out.write("\t\t        <ul>\n");
      out.write("\t\t            <li class=\"links_head\">COMPANY</li>\n");
      out.write("\t\t            <li>CUSTOMER HELP</li>\n");
      out.write("\t\t            <li>PARTNER HELP</li>\n");
      out.write("\t\t            <li>SUGGEST STH</li>\n");
      out.write("\t\t        </ul>\n");
      out.write("\t     </div>\n");
      out.write("    </div>\n");
      out.write("    <hr>\n");
      out.write("        <div class=\"row\">\n");
      out.write("        <div class=\"footer__disclaimer\">\n");
      out.write("        <strong>JABA connects customers with popular cafe brands.</strong>\n");
      out.write("        <p>\n");
      out.write("        We believe that time is precious. We strive to create beautiful technology that helps you save time and make ordering easy, both sides of the counter. Order from JABA with the best selection of local cafes.\n");
      out.write("        </p>\n");
      out.write("        <div class=\"legal\">\n");
      out.write("        \t<div>\n");
      out.write("        \t\t<div class=\"legal__copyright\">© 2020 JABA Technologies Pty Ltd</div>\n");
      out.write("        \t\t<ul class=\"legal__links\">\n");
      out.write("\t        \t\t<li><a class=\"MuiTypography-root MuiLink-root MuiLink-underlineNone MuiTypography-colorPrimary\" href=\"/legal/privacy-policy\">Privacy Policy</a></li>\n");
      out.write("\t        \t\t<li><a class=\"MuiTypography-root MuiLink-root MuiLink-underlineNone MuiTypography-colorPrimary\" href=\"/legal/terms-and-conditions\">Terms of Use</a></li>\n");
      out.write("\t        \t\t<li><a class=\"MuiTypography-root MuiLink-root MuiLink-underlineNone MuiTypography-colorPrimary\" href=\"https://help.bopple.com/\" target=\"_blank\" rel=\"noopener noreferrer\">Help Centre</a></li>\n");
      out.write("\t        \t\t<li><a class=\"MuiTypography-root MuiLink-root MuiLink-underlineNone MuiTypography-colorPrimary\" href=\"https://customer-contact-help.bopple.com\" target=\"_blank\" rel=\"noopener noreferrer\">Leave Feedback</a></li>\n");
      out.write("        \t\t</ul>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t</div>\n");
      out.write("        </div>\n");
      out.write("        \t\n");
      out.write("        </div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t</footer>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
