/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-14 05:44:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>store_menu</title>\n");
      out.write("<script src='https://code.jquery.com/jquery-3.4.0.js'></script>\n");
      out.write("<!-- RESET -->\n");
      out.write("<link href=\"./css/html5_reset.css\" rel=\"stylesheet\">\n");
      out.write("<!-- HEADER CSS -->\n");
      out.write("<link href=\"./css/header.css\" rel=\"stylesheet\">\n");
      out.write("<!-- SECTION CSS -->\n");
      out.write("<link href=\"./css/section.css\" rel=\"stylesheet\">\n");
      out.write("<!-- FOOTER CSS -->\n");
      out.write("<link href=\"./css/footer.css\" rel=\"stylesheet\">\n");
      out.write("<script>\n");
      out.write("$(function(){\n");
      out.write("   $(window).scroll(function(){\n");
      out.write("   var navbar = $(this).scrollTop();\n");
      out.write("   console.log(navbar);\n");
      out.write("   var $header = $('header');\n");
      out.write("   if(navbar > 0){\n");
      out.write("       $header.addClass('activated');\n");
      out.write("   }else{\n");
      out.write("       $header.removeClass('activated');\n");
      out.write("   }\n");
      out.write("   $(\".search-term\").click(function(){\n");
      out.write("\t   $(\"#hidden_term\").attr(\"style\", \"visibility:visible\")\n");
      out.write("   })\n");
      out.write("   $(\".hidden_term_close\").click(function(){\n");
      out.write("\t   $(\"#hidden_term\").attr(\"style\", \"visibility:hidden\")\n");
      out.write("   })\n");
      out.write("   \n");
      out.write(" })\n");
      out.write("})\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("\tmargin: 0;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 100%;\n");
      out.write("\tline-height: 1.43;\n");
      out.write("\t    color: rgba(0, 0, 0, 0.87);\n");
      out.write("    margin: 0;\n");
      out.write("    font-size: 0.875rem;\n");
      out.write("    font-family: Inter,sans-serif;\n");
      out.write("    font-weight: 400;\n");
      out.write("    line-height: 1.43;\n");
      out.write("}\n");
      out.write("div {\n");
      out.write("\tdisplay: block;\n");
      out.write("}\n");
      out.write("input {\n");
      out.write("\tborder: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<!-- MAIN -->\n");
      out.write("<style>\n");
      out.write("main {\n");
      out.write("\twidth: 100%;\n");
      out.write("\tmax-width: 100vw;\n");
      out.write("}\n");
      out.write("section {\n");
      out.write("    padding: 45px 0;\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    align-items: center;\n");
      out.write("    position: relative;\n");
      out.write("    background: #f9fafc;\n");
      out.write("    z-index: 0;\n");
      out.write("}\n");
      out.write("#home {\n");
      out.write("\theight: 300px;\n");
      out.write("}\n");
      out.write("a {\n");
      out.write("\ttext-decoration:none;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<!-- SECTION 2 -->\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".mini{\n");
      out.write("\tpadding: 3px 0;\n");
      out.write("\tbackground-color: white;\n");
      out.write("\tposition: -webkit-sticky;\n");
      out.write("\tposition: sticky;\n");
      out.write("\ttop: 55px;\n");
      out.write("\tz-index: 999;\n");
      out.write("}\n");
      out.write(".mini .container{\n");
      out.write("\twidth:80%;\n");
      out.write("}\n");
      out.write(".mini_row{\n");
      out.write("\tdisplay: flex;\n");
      out.write("\tflex-direction: row;\n");
      out.write("\tpadding: 3px 0;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mini_row button{\n");
      out.write("\tborder: 1px solid rgba(132,146,166,.2)!important;\n");
      out.write("\tcolor: black;\n");
      out.write("\tmargin: 0 8px 0 0;\n");
      out.write("\tfont-weight: normal;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write(".search-term {\n");
      out.write("  display: inline-flex;\n");
      out.write("  align-items: center;\n");
      out.write("  text-align: center;\n");
      out.write("  flex-direction: row;\n");
      out.write("  position: relative\n");
      out.write("}\n");
      out.write(".search-term button{\n");
      out.write("\twidth: 34px;\n");
      out.write("\t--verticalPadding: 0;\n");
      out.write("\t--horizontalPadding: 0;\n");
      out.write("\theight: 34px;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write(".search-term svg{\n");
      out.write("\twidth: 20px;\n");
      out.write("\theight: 20px;\n");
      out.write("\tpadding: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-term {\n");
      out.write("\tborder-radius: 50px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#hidden_term{\n");
      out.write("\tvisibility : hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<!-- SECTION 3 -->\n");
      out.write("<style>\n");
      out.write("#sth{\n");
      out.write("\twidth: 100%;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("#store_information{\n");
      out.write("\twidth: 100%;\n");
      out.write("\tflex-direction: column;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".store_information{\n");
      out.write("\tflex-dircetion: column;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#sth .container{\n");
      out.write("\twidth: 80%;\n");
      out.write("\tmargin: 0 auto;\n");
      out.write("\tpadding-top: 15px;\n");
      out.write("\n");
      out.write("}\n");
      out.write("section#store-list {\n");
      out.write("    padding-top: 65px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("section .container .store_list_grid {\n");
      out.write("    display: grid;\n");
      out.write("    grid-column-gap: 30px;\n");
      out.write("    grid-row-gap: 30px;\n");
      out.write("    grid-template-rows: auto;\n");
      out.write("    min-height: 0;\n");
      out.write("    min-width: 0;\n");
      out.write("    grid-template-columns: repeat(3,1fr);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".store_card_image img{\n");
      out.write("    height: 210px;\n");
      out.write("    border-radius: 6px;\n");
      out.write("    width: 100%;\n");
      out.write("    background: #ebf3fe;\n");
      out.write("    border: 0;\n");
      out.write("    position: relative;\n");
      out.write("    transition: .2s ease-in-out;\n");
      out.write("    height: 160px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<!-- SECTION2 menu_info -->\n");
      out.write("    <style>\n");
      out.write("        #menu_info {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 100vw;\n");
      out.write("            /*\n");
      out.write("        background-color: rgba(219, 242, 255, 0.952);\n");
      out.write("        */\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #container_menu_info {\n");
      out.write("            background-color: rgb(249, 250, 252);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .category h2 {\n");
      out.write("            border-bottom: 1px solid rgb(225, 229, 235);\n");
      out.write("            padding: 15px 0;\n");
      out.write("            font-size: 1.4rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .category_products {\n");
      out.write("            display: grid;\n");
      out.write("            grid-column-gap: 30px;\n");
      out.write("            grid-row-gap: 30px;\n");
      out.write("            grid-template-rows: auto;\n");
      out.write("            grid-template-columns: repeat(2, 1fr);\n");
      out.write("            min-height: 0;\n");
      out.write("            /* NEW */\n");
      out.write("            min-width: 0;\n");
      out.write("            /* NEW; needed for Firefox */\n");
      out.write("            margin: 20px 0px 0px;\n");
      out.write("            /* 창줄였을때 안삐져나가게 */\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("        .product_card {\n");
      out.write("            position: relative;\n");
      out.write("            display: flex;\n");
      out.write("            border: 1px solid;\n");
      out.write("            flex-direction: row;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            overflow: hidden;\n");
      out.write("            background-color: white;\n");
      out.write("            max-height: 145px;\n");
      out.write("            min-width: 345px;\n");
      out.write("            /* 반응형 추가필요 */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product_card_detail {\n");
      out.write("            padding: 15px 25px 15px 15px;\n");
      out.write("            max-height: 145px;\n");
      out.write("            max-width: calc(100% - 145px);\n");
      out.write("            flex-direction: column;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            display: inline-flex;\n");
      out.write("            /* 반응형 추가필요*/\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product_name {\n");
      out.write("            margin-bottom: 2px;\n");
      out.write("            min-width: 160px;\n");
      out.write("            display: flex;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product_name .sold_out_btn{\n");
      out.write("            background-color: #36727C;\n");
      out.write("            border: 1px solid rgb(230, 233, 237);\n");
      out.write("            color: white;\n");
      out.write("            padding: 2px 10px 2px;\n");
      out.write("            text-align: center;\n");
      out.write("            text-decoration: none;\n");
      out.write("            display: inline-block;\n");
      out.write("            margin: 4px 2px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            border-radius: 30px;\n");
      out.write("            outline: 0; /* 테두리 클릭시 없애기 */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product_name .sold_out_btn:hover{\n");
      out.write("            background-color:rgb(235, 235, 235);\n");
      out.write("            border: 1px solid rgb(214, 217, 221);\n");
      out.write("            color:black;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product_name > p {\n");
      out.write("            margin: 0;\n");
      out.write("            font-size: 0.875rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("            /* 반응형 추가필요\n");
      out.write("            */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product_desc {\n");
      out.write("            color: grey;\n");
      out.write("            font-size: 0.75rem;\n");
      out.write("            line-height: 1.05rem;\n");
      out.write("            max-height: 2.1rem;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            position: relative;\n");
      out.write("            margin-right: -1em;\n");
      out.write("            /* 반응형 추가필요 */\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product_price {\n");
      out.write("            font-size: 0.875rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            color: #36727C;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product_card_image {\n");
      out.write("            /* 기본 백그라운드에 대한 처리 모바일 120*/\n");
      out.write("            height: 145px;\n");
      out.write("            width: 145px;\n");
      out.write("            min-width: 145px;\n");
      out.write("            min-height: 145px;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("        .product_card_image img {\n");
      out.write("            width: 145px;\n");
      out.write("            height: 145px;\n");
      out.write("            object-fit: contain;\n");
      out.write("            object-position: center;\n");
      out.write("            /* 트랜지션 처리*/\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- HEADER -->\n");
      out.write("\t<header>\n");
      out.write("\t\t<div class=\"header_container\">\n");
      out.write("\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t<img src=\"./images/jaba_english_white.png\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"menu\">\n");
      out.write("\t\t\t\t<button class=\"menu_btn\" value=\"LOG IN\">\n");
      out.write("\t\t\t\t<span>LOG IN</span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t<button class=\"menu_btn\" value=\"SIGN UP\">\n");
      out.write("\t\t\t\t<span>SIGN UP</span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</header>\n");
      out.write("<!-- SECTION -->\n");
      out.write("\t<section id=\"home\">\n");
      out.write("\t\t<img >\n");
      out.write("\n");
      out.write("\t</section>\n");
      out.write("<!-- SECTION 2 -->\n");
      out.write("\t<section id=\"search\" class=\"mini\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"mini_row\">\n");
      out.write("\t\t\t\t<div class=\"time\">\n");
      out.write("\t\t\t\t\t<button>Pick up, ASAP</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"search_loc\">\n");
      out.write("\t\t\t\t\t<button>AVENUE</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"search-term\">\n");
      out.write("\t\t\t\t<button class=\"MuiButtonBase-root MuiIconButton-root search-term__icon  MuiIconButton-sizeSmall jss263\" tabindex=\"0\" type=\"button\">\n");
      out.write("\t\t\t\t<span class=\"MuiIconButton-label\">\n");
      out.write("\t\t\t\t<svg class=\"MuiSvgIcon-root\" focusable=\"false\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" role=\"presentation\">\n");
      out.write("\t\t\t\t<path d=\"M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z\">\n");
      out.write("\t\t\t\t</path>\n");
      out.write("\t\t\t\t</svg>\n");
      out.write("\t\t\t\t</span>\n");
      out.write("\t\t\t\t<div class=\"MuiTouchRipple-root\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"hidden_term\">\n");
      out.write("\t\t\t\t<button class=\"hidden_term_all\">\n");
      out.write("\t\t\t\t\t<div id=\"hidden_input\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"Acai or Latte\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<button class=\"hidden_term_close\">\n");
      out.write("\t\t\t\t\tX\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("<!-- SECTION 3 -->\n");
      out.write("\t <!-- SECTION1 Store_info -->\n");
      out.write("    <section id=\"store_info\">\n");
      out.write("        <div class=\"container\" id=\"container_store_info\">\n");
      out.write("            <h1>\n");
      out.write("                <!--매장 이름-->\n");
      out.write("                스타벅스 종각점&nbsp;\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-pencil menu_update_icon\" style=\"font-size: 28px;\"></i></a>\n");
      out.write("            </h1>\n");
      out.write("            <span id=\"store_description\">\n");
      out.write("                <!-- 매장 설명-->\n");
      out.write("                스타벅스 종각점입니다. 스타벅스 종각점입니다. 스타벅스 종각점입니다. 스타벅스 종각점입니다. 스타벅스 종각점입니다. 스타벅스 종각점입니다. 스타벅스 종각점입니다.\n");
      out.write("            </span>\n");
      out.write("            <span>\n");
      out.write("                <!-- 최근 게시판부분-->\n");
      out.write("                <h3>재고 소진으로 인해 금일 영업은 20시까지만 합니다. </h3>\n");
      out.write("            </span>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- SECTION2 menu_info -->\n");
      out.write("    <section id=\"menu_info\">\n");
      out.write("        <div class=\"container\" id=\"container_menu_info\">\n");
      out.write("            <div class=\"category\">\n");
      out.write("                <div class=\"category_name\">\n");
      out.write("                    <h2> 메뉴카테고리 : 커피</h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"category_products\">\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product_card\">\n");
      out.write("                        <div class=\"product_card_detail\">\n");
      out.write("                            <div class=\"product_name\">\n");
      out.write("                                <p>아메리카노&nbsp;&nbsp;<button class=\"sold_out_btn\">Sold out</button></p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_desc\">\n");
      out.write("                                아메리카노는 에스프레소 + 물이다.\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product_price\">\n");
      out.write("                                <p>4000원</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"product_card_image\">\n");
      out.write("                            <img src=\"https://cdn.boppl.me/products/specialty_affogato_0.jpg\" alt=\"Affogato\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!--category 끝 -->\n");
      out.write("                </div>\n");
      out.write("\t\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t\n");
      out.write("\t\t<!-- FOOTER -->\n");
      out.write("\t<footer> \n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t        <div class=\"footer_logo\">\n");
      out.write("\t            <img src=\"images/jaba_english_white.png\">\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"footer_links\">\n");
      out.write("\t\t        <ul>\n");
      out.write("\t\t            <li class=\"links_head\">JABA for YOUNG&RICH</li>\n");
      out.write("\t\t            <li>WHY JABA?</li>\n");
      out.write("\t\t            <li>PRICING</li>\n");
      out.write("\t\t            <li><a href='#'>PARTNER LOGIN</a></li>\n");
      out.write("\t\t        </ul>\n");
      out.write("\t\t        <ul>\n");
      out.write("\t\t            <li class=\"links_head\">TOP CITIES</li>\n");
      out.write("\t\t            <li>JONGRO</li>\n");
      out.write("\t\t            <li>SEOCHON</li>\n");
      out.write("\t\t            <li>PARIS</li>\n");
      out.write("\t\t        </ul>\n");
      out.write("\t\t        <ul>\n");
      out.write("\t\t            <li class=\"links_head\">SUPPORT</li>\n");
      out.write("\t\t            <li>CUSTOMER HELP</li>\n");
      out.write("\t\t            <li>PARTNER HELP</li>\n");
      out.write("\t\t            <li>SUGGEST STH</li>\n");
      out.write("\t\t        </ul>\n");
      out.write("\t\t        <ul>\n");
      out.write("\t\t            <li class=\"links_head\">COMPANY</li>\n");
      out.write("\t\t            <li>CUSTOMER HELP</li>\n");
      out.write("\t\t            <li>PARTNER HELP</li>\n");
      out.write("\t\t            <li>SUGGEST STH</li>\n");
      out.write("\t\t        </ul>\n");
      out.write("\t     </div>\n");
      out.write("    </div>\n");
      out.write("    <hr>\n");
      out.write("        <div class=\"row\">\n");
      out.write("        <div class=\"footer__disclaimer\">\n");
      out.write("        <strong>JABA connects customers with popular cafe brands.</strong>\n");
      out.write("        <p>\n");
      out.write("        We believe that time is precious. We strive to create beautiful technology that helps you save time and make ordering easy, both sides of the counter. Order from JABA with the best selection of local cafes.\n");
      out.write("        </p>\n");
      out.write("        <div class=\"legal\">\n");
      out.write("        \t<div>\n");
      out.write("        \t\t<div class=\"legal__copyright\">© 2020 JABA Technologies Pty Ltd</div>\n");
      out.write("        \t\t<ul class=\"legal__links\">\n");
      out.write("\t        \t\t<li><a class=\"MuiTypography-root MuiLink-root MuiLink-underlineNone MuiTypography-colorPrimary\" href=\"/legal/privacy-policy\">Privacy Policy</a></li>\n");
      out.write("\t        \t\t<li><a class=\"MuiTypography-root MuiLink-root MuiLink-underlineNone MuiTypography-colorPrimary\" href=\"/legal/terms-and-conditions\">Terms of Use</a></li>\n");
      out.write("\t        \t\t<li><a class=\"MuiTypography-root MuiLink-root MuiLink-underlineNone MuiTypography-colorPrimary\" href=\"https://help.bopple.com/\" target=\"_blank\" rel=\"noopener noreferrer\">Help Centre</a></li>\n");
      out.write("\t        \t\t<li><a class=\"MuiTypography-root MuiLink-root MuiLink-underlineNone MuiTypography-colorPrimary\" href=\"https://customer-contact-help.bopple.com\" target=\"_blank\" rel=\"noopener noreferrer\">Leave Feedback</a></li>\n");
      out.write("        \t\t</ul>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t</div>\n");
      out.write("        </div>\n");
      out.write("        \t\n");
      out.write("        </div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t</footer>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
